### ISSUE TITLE
请教个使用问题

### ISSUE THREAD

**Issue by ADolphin-02** [johnsmithsren/dy#1]
跑起来如何使用呢，4000端口的
![image](https://user-images.githubusercontent.com/55866634/226292789-615e60b3-be66-4041-8acd-432aee2cb528.png)

**Comment by johnsmithsren** [comment]
首先需要使用另外一个端口去开启直播监听，可以看下代码  room/start?roomId=xxxxxx,然后再去获取弹幕

**Comment by ADolphin-02** [comment]
大佬，还是不太明白，就是我都会运行，代码就懂一点点的、都是怎么才能获取弹幕呢，我不会这个语言的，我会点前端
![image](https://user-images.githubusercontent.com/55866634/226794365-b2e713cc-8c3b-4cad-a4de-f0e1aab92c4a.png)

**Comment by ADolphin-02** [comment]
我就看懂读取redis的，然后设置

**Comment by johnsmithsren** [comment]
你不是知道房间号吗，比如95676开头这个，先请求这个 room/start?roomId=95676  然后再请求  /95676  就能获取弹幕了
